name: mkt_modeling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - matplotlib-base
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - networkx
  - mdanalysis
  - pymol-open-source
  - rdkit
  - h5py
  - netcdf4
  - pillow
  - setuptools
  - pip
  - packaging
  - tqdm
  - joblib
  - filelock
  - gitpython
  - sqlalchemy
  - statsmodels
  - reportlab
  - prolif
  - pyqt
  - contourpy
  - kiwisolver
  - pyparsing
  - python-dateutil
  - pytz
  - six
  - cycler
  - fonttools
  - certifi
  - chardet
  - colorama
  - dill
  - greenlet
  - mmtf-python
  - mrcfile
  - msgpack-python
  - multiprocess
  - munkres
  - patsy
  - ply
  - threadpoolctl
  - tidynamics
  - toml
  - tomli
  - typing-extensions
  - wheel
  - unicodedata2
  - griddataformats
  - gsd
  - mda-xdrlib
  - pyedr
  - pytng
  - rlpycairo
  - pycairo
  - smmap
  - cached-property
  - ipykernel
  - jupyter
  - mols2grid
