import pytest
import requests as req_lib
from mkt.databases import ncbi


@pytest.fixture(scope="module")
def ncbi_brsk2():
    """Fetch NCBI protein record for EAX02438.1 once."""
    try:
        return ncbi.ProteinNCBI(accession="EAX02438.1")
    except req_lib.exceptions.RetryError as e:
        if "500 error responses" in str(e):
            pytest.skip("NCBI API returned 500 errors - skipping test")
        raise


@pytest.mark.network
class TestProteinNCBI:
    def test_header(self, ncbi_brsk2):
        assert ncbi_brsk2.list_headers == [
            "EAX02438.1 BR serine/threonine kinase 2, isoform CRA_c [Homo sapiens]"
        ]

    def test_sequence(self, ncbi_brsk2):
        assert ncbi_brsk2.list_seq == [
            "MTSTGKDGGAQHAQYVGPYRLEKTLGKGQTGLVKLGVHCVTCQKVAIKIVNREKLSESVLMKVEREIAILKLIEHPHVLKLHDVYENKKYLYLVLEHVSGGELFDYLVKKGRLTPKEARKFFRQIISALDFCHSHSICHRDLKPENLLLDEKNNIRIADFGMASLQVGDSLLETSCGSPHYACPEVIRGEKYDGRKADVWSCGVILFALLVGALPFDDDNLRQLLEKVKRGVFHMPHFIPPDCQSLLRGMIEVDAARRLTLEHIQKHIWYIGGKNEPEPEQPIPRKVQIRSLPSLEDIDPDVLDSMHSLGCFRDRNKLLQDLLSEEENQEKMIYFLLLDRKERYPSQEDEDLPPRNEIDPPRKRVDSPMLNRHGKRRPERKSMEVLSVTDGGSPVPARRAIEMAQHGQRSRSISGASSGLSTSPLSSPRVTPHPSPRGSPLPTPKGTPVHTPKESPAGTPNPTPPSSPSVGGVPWRARLNSIKNSFLGSPRFHRRKLQVPTPEEMSNLTPESSPELAKKSWFGNFISLEKEEQIFVVIKDKPLSSIKADIVHAFLSIPSLSHSVISQTSFRAEYKATGGPAVFQKPVKFQVDITYTEGGEAQKENGIYSVTFTLLSGPSRRFKRVVETIQAQLLSTHDPPAAQHLSEPPPPAPGLSWGAGLKGQKVATSYESSL"
        ]
