name: mkt_ml_plus
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - accelerate=0.33.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - anyio=4.9.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=23.2.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - brotli=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=2.20.0
  - debugpy=1.8.13
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - freetype-py=2.3.0
  - frozenlist=1.4.1
  - fuzzywuzzy=0.18.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - greenlet=3.1.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.24.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.5
  - kneed=0.8.5
  - krb5=1.21.3
  - lcms2=2.16
  - levenshtein=0.27.1
  - lightning=2.5.1.post0
  - lightning-utilities=0.14.3
  - llvmlite=0.44.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.3.3
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl
  - overrides=7.7.0
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathtools=0.1.2
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycairo=1.27.0
  - pycparser=2.22
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-levenshtein=0.27.1
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.12
  - pytorch=2.4.0
  - pytorch-lightning=2.5.1.post0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.3.0
  - rapidfuzz=3.13.0
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.7.24
  - reportlab=4.3.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rlpycairo=0.2.0
  - rpds-py=0.23.1
  - safetensors=0.4.3
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - sentry-sdk=2.11.0
  - setproctitle=1.3.3
  - setuptools=71.0.4
  - six=1.16.0
  - smmap=5.0.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlalchemy=2.0.39
  - stack_data=0.6.3
  - strenum=0.4.15
  - sympy=1.13.0
  - tbb=2021.12.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.19.1
  - tomli=2.2.1
  - torchmetrics=1.7.2
  - tornado=6.4.2
  - tqdm=4.66.4
  - traitlets=5.14.3
  - transformers=4.43.3
  - types-python-dateutil
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - umap-learn=0.5.7
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wandb=0.16.6
  - wcwidth=0.2.13
  - webcolors
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.13
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiobotocore==2.23.1
      - aioitertools==0.12.0
      - alabaster==0.7.16
      - anndata==0.12.0
      - annotated-types==0.7.0
      - array-api-compat==1.12.0
      - biopython==1.85
      - biothings-client==0.4.1
      - black==24.3.0
      - botocore==1.38.46
      - cellxgene-census==1.17.0
      - crc32c==2.7.1
      - dataclasses==0.6
      - docutils==0.20.1
      - donfig==0.8.1.post1
      - et-xmlfile==2.0.0
      - flake8==7.0.0
      - fsspec==2025.7.0
      - gget==0.29.2
      - h5py==3.14.0
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - jmespath==1.0.1
      - legacy-api-wrap==1.4.1
      - lxml==6.0.0
      - mccabe==0.7.0
      - more-itertools==10.7.0
      - mygene==3.2.2
      - mypy-extensions==1.0.0
      - mysql-connector-python==9.4.0
      - natsort==8.4.0
      - numcodecs==0.16.1
      - openpyxl==3.1.5
      - packaging==25.0
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pycodestyle==2.11.1
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pyflakes==3.2.0
      - pytdc==1.0.0
      - pytest==8.0.1
      - pytest-runner==6.0.1
      - rdkit==2023.9.6
      - s3fs==2025.7.0
      - scanpy==1.11.3
      - scikit-learn==1.2.2
      - session-info2==0.1.2
      - shapely==2.1.1
      - snowballstemmer==2.2.0
      - somacore==1.0.28
      - sphinx==7.3.7
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - statsmodels==0.14.5
      - tiledbsoma==1.17.0
      - toml==0.10.2
      - typing-inspection==0.4.1
      - wrapt==1.17.2
      - yapf==0.43.0
      - zarr==3.1.0
