#!/usr/bin/env bash
# Usage: docs/build_docs.sh
#
# Builds the Sphinx HTML docs using the docs venv at docs/.venv. Run
# docs/create_docs_venv.sh first if that venv does not exist.
#
# Performs a clean build: removes the previous _build/ and the autogenerated
# generated/ stubs (both untracked) so that added/removed API is reflected.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/.venv"
VENV_PY="$VENV_DIR/bin/python"

if [ ! -x "$VENV_PY" ]; then
  echo "docs venv not found at $VENV_DIR" >&2
  echo "run docs/create_docs_venv.sh first" >&2
  exit 1
fi

cd "$SCRIPT_DIR"

# clean previous output and autosummary stubs (regenerated on build)
rm -rf _build generated

# guards read by the package to skip cohort/network data loading during build:
# SPHINX_BUILD skips the DiscoverX network query, MKT_SKIP_KINASE_DICT skips the
# kinase-dict deserialization
export SPHINX_BUILD=1
export MKT_SKIP_KINASE_DICT=1

echo "building Sphinx HTML docs..."
"$VENV_PY" -m sphinx -b html . _build/html

echo "done. view at: file://$SCRIPT_DIR/_build/html/index.html"
if command -v open >/dev/null 2>&1; then
  open _build/html/index.html
elif command -v xdg-open >/dev/null 2>&1; then
  xdg-open _build/html/index.html
fi
