name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

  # docs
  - sphinx
  - sphinx_rtd_theme
  - myst-parser
  - nbsphinx
  - nbsphinx-link
  - pandoc


    # Pip-only installs
  #- pip:
