name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python >=3.10,<3.11
  - pip

    # docs
  - sphinx
  - sphinx_rtd_theme
  - myst-parser
  - nbsphinx
  - nbsphinx-link
  - pandoc

    # Pip-only installs
  #- pip:
