name: databases-ci

on:
  push:
    branches:
      - "main"
    paths:
      - "missense_kinase_toolkit/databases/**"
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - "missense_kinase_toolkit/databases/**"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          environment-name: test
          channels: conda-forge,defaults
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install ./missense_kinase_toolkit/schema --no-deps
          python -m pip install ./missense_kinase_toolkit/databases --no-deps
          micromamba list

      - name: Run tests
        shell: bash -l {0}
        run: |
          set -e
          pytest \
            -v \
            --cov-report=xml \
            --color=yes  \
            --cov=mkt.databases \
            -F databases \
            missense_kinase_toolkit/databases/mkt/databases/tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.3
        with:
          fail_ci_if_error: false # optional (default = false)
          file: ./coverage.xml
          flags: databases # optional
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
