name: databases-ci

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  # The cookiecutter uses the "--initial-branch" flag when it runs git-init
  push:
    branches:
      - "main"
    paths:
      - "missense_kinase_toolkit/databases/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "missense_kinase_toolkit/databases/**"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/provision-with-micromamba
      # https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba%60
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          environment-name: test
          # conda-forge is the default channel now and does not need to be specified
          channels: conda-forge,defaults
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Run tests
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          pytest -v --cov-report=xml --color=yes  \
          --cov=missense_kinase_toolkit/databases \
           missense_kinase_toolkit/databases/missense_kinase_toolkit/databases/tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: false # optional (default = false)
          file: ./coverage.xml
          flags: databases # optional
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
          # https://github.com/codecov/codecov-action
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
